<a href="https://colab.research.google.com/github/Parteche/Diplomado-Ciencia-De-Datos-BEDU/blob/main/Copia_de_Copia_de_modulo2_Michel_Pau.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Modulo 2 Procesamiento de datos con Python
Proyecto de Michel Acosta Trasvi√±a y Paulina Adams Arteche

Para este proyecto escogimos una base de datos de goodreads y la descargamos en formato CSV de la plataforma kaggle.

Nuestra base de datos books y contiene informacion muy interesante sobre los libros mejor calificados en el idioma ingles.

In [104]:
#Primero que nada importamos pandas, la libreria mas importante para el manejo de datos.
import pandas as pd
#importamos numpys es otra libreria que se utiliza para operaciones matematicas, aun no sabemos si la usaremos pero la descargamos por si a caso
import numpy as np

In [79]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [80]:
#Importamos la base de datos CSV
df = pd.read_csv('/content/drive/MyDrive/Books_Data_Clean.csv')

In [81]:
#Metodo para ver las 5 primeras filas de la base de datos
df.head()
#Sirve para darle un primer vistazo a la base de datos que recien importados

,index,Publishing Year,Book Name,Author,language_code,Author_Rating,Book_average_rating,Book_ratings_count,genre,gross sales,publisher revenue,sale price,sales rank,Publisher,units sold
0,0,1975.0,Beowulf,"Unknown, Seamus Heaney",en-US,Novice,3.42,155903,genre fiction,34160.0,20496.0,4.88,1,HarperCollins Publishers,7000
1,1,1987.0,Batman: Year One,"Frank Miller, David Mazzucchelli, Richmond Lew...",eng,Intermediate,4.23,145267,genre fiction,12437.5,7462.5,1.99,2,HarperCollins Publishers,6250
2,2,2015.0,Go Set a Watchman,Harper Lee,eng,Novice,3.31,138669,genre fiction,47795.0,28677.0,8.69,3,"Amazon Digital Services, Inc.",5500
3,3,2008.0,When You Are Engulfed in Flames,David Sedaris,en-US,Intermediate,4.04,150898,fiction,41250.0,24750.0,7.50,3,Hachette Book Group,5500
4,4,2011.0,Daughter of Smoke & Bone,Laini Taylor,eng,Intermediate,4.04,198283,genre fiction,37952.5,22771.5,7.99,4,Penguin Group (USA) LLC,4750

In [82]:
#Queremos saber que tipo de columnas tenemos:
df.dtypes

index                    int64
Publishing Year        float64
Book Name               object
Author                  object
language_code           object
Author_Rating           object
Book_average_rating    float64
Book_ratings_count       int64
genre                   object
gross sales            float64
publisher revenue      float64
sale price             float64
sales rank               int64
Publisher               object
units sold               int64
dtype: object

In [83]:
#La columna Publishing Year (a√±o de publicacion) tiene tipo de dato float64 es decir decimal y deberia ser int64 osea entero (los a√±os siempre son numeros enteros)
#Con el metodo .astype() cambiamos el tipo de dato y con el metodo .fillna() logramos que no nos afecte
#los registros que tienen NA
df['Publishing Year'] = df['Publishing Year'].fillna(0).astype('int64')
#Checamos de nuevo nuestros tipos de datos para confirmar que si cambio el tipo de dato de la columna 'Publishing Year'
print(df.dtypes)

index                    int64
Publishing Year          int64
Book Name               object
Author                  object
language_code           object
Author_Rating           object
Book_average_rating    float64
Book_ratings_count       int64
genre                   object
gross sales            float64
publisher revenue      float64
sale price             float64
sales rank               int64
Publisher               object
units sold               int64
dtype: object

In [84]:
#Checamos de nuevo los primeros 5 registros de nuestra base de datos
df.head()
#Ahora si la columna de 'Publishing Year' tiene un tipo de dato adecuado

,index,Publishing Year,Book Name,Author,language_code,Author_Rating,Book_average_rating,Book_ratings_count,genre,gross sales,publisher revenue,sale price,sales rank,Publisher,units sold
0,0,1975,Beowulf,"Unknown, Seamus Heaney",en-US,Novice,3.42,155903,genre fiction,34160.0,20496.0,4.88,1,HarperCollins Publishers,7000
1,1,1987,Batman: Year One,"Frank Miller, David Mazzucchelli, Richmond Lew...",eng,Intermediate,4.23,145267,genre fiction,12437.5,7462.5,1.99,2,HarperCollins Publishers,6250
2,2,2015,Go Set a Watchman,Harper Lee,eng,Novice,3.31,138669,genre fiction,47795.0,28677.0,8.69,3,"Amazon Digital Services, Inc.",5500
3,3,2008,When You Are Engulfed in Flames,David Sedaris,en-US,Intermediate,4.04,150898,fiction,41250.0,24750.0,7.50,3,Hachette Book Group,5500
4,4,2011,Daughter of Smoke & Bone,Laini Taylor,eng,Intermediate,4.04,198283,genre fiction,37952.5,22771.5,7.99,4,Penguin Group (USA) LLC,4750

**Breve explicacion de lo que contiene cada columna:**

Publishing Year: A√±o en que fue publicado el libro

Book name: El titulo del libro

Author: El nombre del autor

Lenguage_code: El idioma en que esta escrito el libro

Author_Rating: Calificacion del autor por sus obras anteriores

Book_average_rating: El promedio de rating calificado por los lectores

Book_ratings_count: El numero de ratings que los lectores dieron al libro

genre: El genero o categoria del libro

gross sales: El total de ganancias de ventas de cada libro

publisher revenue: Los ingresos obtenidos por los editores por la venta de cada libro

sale price: El precio en que se vende cada libro

sales rank: Valor numerico que indica la clasificacion de un libro en funcion de su rendimiento en ventas dentro de su propia categoria

Publisher: Editorial

units sold: Numero total de copias vendidas

Criterios que tomaremos en cuenta para la limpieza de nuestros datos:

In [85]:
#Datos faltantes
#Verificar valores nulos en todas las columnas:
print(df.isnull().sum())
#El resultado nos arroja que la columna 'Book Name' tiene 23 registros nulos y la columna language_code tiene 53

index                   0
Publishing Year         0
Book Name              23
Author                  0
language_code          53
Author_Rating           0
Book_average_rating     0
Book_ratings_count      0
genre                   0
gross sales             0
publisher revenue       0
sale price              0
sales rank              0
Publisher               0
units sold              0
dtype: int64

In [86]:
#Usaremos el metodo .info() para tener mas informacion sobre nuestra base de datos
df.info()
#Vemos que nuestra base de datos tiene 1070 filas y 15 columnas, por lo que valdria la pena eliminar los
#registros nulos, ya que tenemos suficientes datos para seguir trabajando

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1070 entries, 0 to 1069
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   index                1070 non-null   int64
 1   Publishing Year      1070 non-null   int64
 2   Book Name            1047 non-null   object
 3   Author               1070 non-null   object
 4   language_code        1017 non-null   object
 5   Author_Rating        1070 non-null   object
 6   Book_average_rating  1070 non-null   float64
 7   Book_ratings_count   1070 non-null   int64
 8   genre                1070 non-null   object
 9   gross sales          1070 non-null   float64
 10  publisher revenue    1070 non-null   float64
 11  sale price           1070 non-null   float64
 12  sales rank           1070 non-null   int64
 13  Publisher            1070 non-null   object
 14  units sold           1070 non-null   int64
dtypes: float64(4), int64(5), object(6)
memory usage: 125.5+ KB

In [87]:
#Eliminando registros nulos
df.dropna(inplace=True)
#Verificamos de nuevo registros nulos
print(df.isnull().sum())
#Los resultados son favorables, cada vez tenemos una base de datos mas limpia

index                  0
Publishing Year        0
Book Name              0
Author                 0
language_code          0
Author_Rating          0
Book_average_rating    0
Book_ratings_count     0
genre                  0
gross sales            0
publisher revenue      0
sale price             0
sales rank             0
Publisher              0
units sold             0
dtype: int64

In [88]:
#Registros repetidos:
print(df.duplicated().sum())
#El resultado nos indica que no tenemos datos duplicados en nuestra base de datos

0

In [89]:
#Columnas irrelevantes
#Columnas categoricas
columns_to_check_cat = ['Book Name', 'Author', 'language_code', 'Author_Rating', 'genre', 'Publisher ']

In [90]:
#Si alguna columna categorica nos da un valor igual a 1 esta se considera irrelevante, significa que todos los valores
#son iguales
unique_counts = df[columns_to_check_cat].nunique()
print(unique_counts)

Book Name        996
Author           698
language_code      8
Author_Rating      4
genre              4
Publisher          9
dtype: int64

In [91]:
#Otro criterio para eliminar datos irrelevantes es si no nos sirven para contestar nuestras preguntas, por ejemplo la columna
#language_code, todos los libros estan en ingles, no hace la diferencia esa la informacion de esa columna
#Primero exploraremos la columna language_code:
df['language_code'].value_counts()
#Podemos observar que 4 de los diferentes lenguages son el mismo solo que con error tipografico
#y los otros 4 que en total representan 9 filas son insignificantes para nuestras base de datos, por lo tanto esta columna no nos sirve realmente
#para las consultas que queremos hacer

language_code
eng      725
en-US    228
en-GB     29
en-CA      7
fre        4
spa        2
ara        2
nl         1
Name: count, dtype: int64

In [92]:
#Segundo, explorando la columna Author_Rating:
df['Author_Rating'].value_counts()
#A pesar de que son pocas categorias, si nos podrian servir para nuestras consultas y ademas ninguna se repite

Author_Rating
Intermediate    589
Excellent       333
Famous           47
Novice           29
Name: count, dtype: int64

In [93]:
#Tercero, explorando la columna genre:
df['genre'].value_counts()
#De los 4 diferentes generos que nos arroja, dos significan los mismo, en este caso vamos a unificar esos dos generos para tener solo 3 en total
#No eliminaremos esta columna por que creo que podemos necesitar estos datos

genre
genre fiction    772
nonfiction       156
fiction           55
children          15
Name: count, dtype: int64

In [94]:
#Primero hacemos un diccionario con los diferentes subniveles de genero y con el nombre final que queremos que tenga:
unificando_genero = {
    'genre fiction': 'fiction', 'fiction': 'fiction', 'nonfiction': 'no fiction', 'children': 'children'
}

#Codigo para remplazar nombres (aqui usamos el diccionario que hicimos para que reemplace los registros mal nombrados):
#Usamos en metodo de pandas .raplace(dicccionario)
df['genre'] = df['genre'].replace(unificando_genero)
print("DataFrame after replacement:")
df.head()

DataFrame after replacement:

,index,Publishing Year,Book Name,Author,language_code,Author_Rating,Book_average_rating,Book_ratings_count,genre,gross sales,publisher revenue,sale price,sales rank,Publisher,units sold
0,0,1975,Beowulf,"Unknown, Seamus Heaney",en-US,Novice,3.42,155903,fiction,34160.0,20496.0,4.88,1,HarperCollins Publishers,7000
1,1,1987,Batman: Year One,"Frank Miller, David Mazzucchelli, Richmond Lew...",eng,Intermediate,4.23,145267,fiction,12437.5,7462.5,1.99,2,HarperCollins Publishers,6250
2,2,2015,Go Set a Watchman,Harper Lee,eng,Novice,3.31,138669,fiction,47795.0,28677.0,8.69,3,"Amazon Digital Services, Inc.",5500
3,3,2008,When You Are Engulfed in Flames,David Sedaris,en-US,Intermediate,4.04,150898,fiction,41250.0,24750.0,7.50,3,Hachette Book Group,5500
4,4,2011,Daughter of Smoke & Bone,Laini Taylor,eng,Intermediate,4.04,198283,fiction,37952.5,22771.5,7.99,4,Penguin Group (USA) LLC,4750

In [95]:
#Eliminando columnas irrelevantes: language_code
#Usaremos el metodo de pandas .drop()
df = df.drop('language_code', axis=1)
df.head()

,index,Publishing Year,Book Name,Author,Author_Rating,Book_average_rating,Book_ratings_count,genre,gross sales,publisher revenue,sale price,sales rank,Publisher,units sold
0,0,1975,Beowulf,"Unknown, Seamus Heaney",Novice,3.42,155903,fiction,34160.0,20496.0,4.88,1,HarperCollins Publishers,7000
1,1,1987,Batman: Year One,"Frank Miller, David Mazzucchelli, Richmond Lew...",Intermediate,4.23,145267,fiction,12437.5,7462.5,1.99,2,HarperCollins Publishers,6250
2,2,2015,Go Set a Watchman,Harper Lee,Novice,3.31,138669,fiction,47795.0,28677.0,8.69,3,"Amazon Digital Services, Inc.",5500
3,3,2008,When You Are Engulfed in Flames,David Sedaris,Intermediate,4.04,150898,fiction,41250.0,24750.0,7.50,3,Hachette Book Group,5500
4,4,2011,Daughter of Smoke & Bone,Laini Taylor,Intermediate,4.04,198283,fiction,37952.5,22771.5,7.99,4,Penguin Group (USA) LLC,4750

In [96]:
#Nos hemos dado cuenta que la columna publisher nos da error, y tiene datos irrelevantes asi que la vamos a eliminar, pero primero la examinaremos
#df['Publisher'].value_counts() no podemos verla, nos marca error
#df = df.drop('Publisher', axis=1)
#df.head()
#La columna Publisher esta maldita...
df['Publisher '].value_counts()
#Ya encontramos el error, en el nombre tiene un espacio al final que obvio no escribiamos cuando usabamos el nombre de la columna

Publisher
Amazon Digital Services,  Inc.          566
Random House LLC                        111
Penguin Group (USA) LLC                  97
HarperCollins Publishers                 65
Hachette Book Group                      56
Simon and Schuster Digital Sales Inc     55
Macmillan                                40
HarperCollins Publishing                  4
HarperCollins Christian Publishing        4
Name: count, dtype: int64

In [97]:
#Cambiando el nombre de la columna Publisher para corregir el espacio en blanco:
#Usamos el metodo .rename()
df.rename(columns={'Publisher ': 'Editorial'}, inplace=True)
df.head()

,index,Publishing Year,Book Name,Author,Author_Rating,Book_average_rating,Book_ratings_count,genre,gross sales,publisher revenue,sale price,sales rank,Editorial,units sold
0,0,1975,Beowulf,"Unknown, Seamus Heaney",Novice,3.42,155903,fiction,34160.0,20496.0,4.88,1,HarperCollins Publishers,7000
1,1,1987,Batman: Year One,"Frank Miller, David Mazzucchelli, Richmond Lew...",Intermediate,4.23,145267,fiction,12437.5,7462.5,1.99,2,HarperCollins Publishers,6250
2,2,2015,Go Set a Watchman,Harper Lee,Novice,3.31,138669,fiction,47795.0,28677.0,8.69,3,"Amazon Digital Services, Inc.",5500
3,3,2008,When You Are Engulfed in Flames,David Sedaris,Intermediate,4.04,150898,fiction,41250.0,24750.0,7.50,3,Hachette Book Group,5500
4,4,2011,Daughter of Smoke & Bone,Laini Taylor,Intermediate,4.04,198283,fiction,37952.5,22771.5,7.99,4,Penguin Group (USA) LLC,4750

In [98]:
#Unificaremos algunos nombres repetidos de editoriales:
unificando_editorial = {
    'Random House LLC': 'Penguin Random House', 'Penguin Group (USA) LLC': 'Penguin Random House', 'Amazon Digital Services,  Inc.': 'Amazon KDP', 'Simon and Schuster Digital Sales Inc': 'Simon and Schuter',
    'HarperCollins Christian Publishing ': 'HarperCollins Publishing'
}

#Usamos en metodo de pandas .raplace(dicccionario)
df['Editorial'] = df['Editorial'].replace(unificando_editorial)
print("DataFrame after replacement:")
df.head()

DataFrame after replacement:

,index,Publishing Year,Book Name,Author,Author_Rating,Book_average_rating,Book_ratings_count,genre,gross sales,publisher revenue,sale price,sales rank,Editorial,units sold
0,0,1975,Beowulf,"Unknown, Seamus Heaney",Novice,3.42,155903,fiction,34160.0,20496.0,4.88,1,HarperCollins Publishers,7000
1,1,1987,Batman: Year One,"Frank Miller, David Mazzucchelli, Richmond Lew...",Intermediate,4.23,145267,fiction,12437.5,7462.5,1.99,2,HarperCollins Publishers,6250
2,2,2015,Go Set a Watchman,Harper Lee,Novice,3.31,138669,fiction,47795.0,28677.0,8.69,3,Amazon KDP,5500
3,3,2008,When You Are Engulfed in Flames,David Sedaris,Intermediate,4.04,150898,fiction,41250.0,24750.0,7.50,3,Hachette Book Group,5500
4,4,2011,Daughter of Smoke & Bone,Laini Taylor,Intermediate,4.04,198283,fiction,37952.5,22771.5,7.99,4,Penguin Random House,4750

In [100]:
#Columnas numericas
#Para saber si una columna numerica es irrelevante checamos su desviacion estandar, si esta es igual a cero
#quiere decir que los valores en esa columna son iguales, no hay variacion de numeros, osea es irrelevante
df.describe()
#El metodo .describe() por default toma solo las columnas de valor numerico
#No hay columnas numericas con desviacion estandar igual a cero
#Los valores repetidos en las columnas numericas si pueden ser

,index,Publishing Year,Book_average_rating,Book_ratings_count,gross sales,publisher revenue,sale price,sales rank,units sold
count,998.000000,998.000000,998.000000,998.000000,998.00000,998.000000,998.000000,998.000000,998.000000
mean,529.619238,1971.070140,4.003056,95500.622244,1885.08515,848.897952,4.839649,605.750501,9802.312625
std,308.616860,190.019592,0.247360,31650.845116,4023.26877,2303.504061,3.585046,369.174705,15503.088302
min,0.000000,-560.000000,2.970000,27308.000000,104.94000,0.000000,0.990000,1.000000,106.000000
25%,263.250000,1985.000000,3.850000,70946.500000,370.88250,0.000000,1.990000,283.000000,555.000000
50%,530.500000,2003.000000,4.010000,89901.000000,806.25000,260.619000,3.990000,591.500000,3915.000000
75%,793.750000,2010.000000,4.170000,115596.000000,1492.96500,721.180500,6.990000,919.500000,5420.250000
max,1069.000000,2016.000000,4.770000,206792.000000,47795.00000,28677.000000,33.860000,1273.000000,61560.000000

In [101]:
#Una vez teniendo la base de datos limpia, podemos hacer consultas.
# 1.-¬øCual es el libro con mayor calificacion promedio? (Book_average_rating)
book_best_rating = df.loc[df['Book_average_rating'].idxmax(),]
print(f'El libro con mayor calificacion promedio es: {book_best_rating}')

El libro con mayor calificacion promedio es: index                                       331
Publishing Year                            2014
Book Name                     Words of Radiance
Author                        Brandon Sanderson
Author_Rating                            Famous
Book_average_rating                        4.77
Book_ratings_count                        73572
genre                                   fiction
gross sales                              741.52
publisher revenue                       444.912
sale price                                 2.99
sales rank                                  354
Editorial              HarperCollins Publishers
units sold                                  248
Name: 331, dtype: object

In [107]:
#2.-Queremos saber que cantidad de copias de libros se han vendido por cada decada
df_2 = ['Publishing Year', 'Book Name', 'units sold']