<a href="https://colab.research.google.com/github/Parteche/Diplomado-Ciencia-De-Datos-BEDU/blob/main/Copia_de_Copia_de_modulo2_Michel_Pau.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Modulo 2 Procesamiento de datos con Python
Proyecto de Michel Acosta Trasvi√±a y Paulina Adams Arteche

Para este proyecto escogimos una base de datos de goodreads y la descargamos en formato CSV de la plataforma kaggle.

Nuestra base de datos books y contiene informacion muy interesante sobre los libros mejor calificados en el idioma ingles.

In [186]:
#Primero que nada importamos pandas, la libreria mas importante para el manejo de datos.
import pandas as pd
#importamos numpys es otra libreria que se utiliza para operaciones matematicas, aun no sabemos si la usaremos pero la descargamos por si a caso
import numpy as np

In [187]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [188]:
#Importamos la base de datos CSV
df = pd.read_csv('/content/drive/MyDrive/Books_Data_Clean.csv')

In [189]:
#Metodo para ver las 5 primeras filas de la base de datos
df.head()
#Sirve para darle un primer vistazo a la base de datos que recien importados

,index,Publishing Year,Book Name,Author,language_code,Author_Rating,Book_average_rating,Book_ratings_count,genre,gross sales,publisher revenue,sale price,sales rank,Publisher,units sold
0,0,1975.0,Beowulf,"Unknown, Seamus Heaney",en-US,Novice,3.42,155903,genre fiction,34160.0,20496.0,4.88,1,HarperCollins Publishers,7000
1,1,1987.0,Batman: Year One,"Frank Miller, David Mazzucchelli, Richmond Lew...",eng,Intermediate,4.23,145267,genre fiction,12437.5,7462.5,1.99,2,HarperCollins Publishers,6250
2,2,2015.0,Go Set a Watchman,Harper Lee,eng,Novice,3.31,138669,genre fiction,47795.0,28677.0,8.69,3,"Amazon Digital Services, Inc.",5500
3,3,2008.0,When You Are Engulfed in Flames,David Sedaris,en-US,Intermediate,4.04,150898,fiction,41250.0,24750.0,7.50,3,Hachette Book Group,5500
4,4,2011.0,Daughter of Smoke & Bone,Laini Taylor,eng,Intermediate,4.04,198283,genre fiction,37952.5,22771.5,7.99,4,Penguin Group (USA) LLC,4750

In [190]:
#Queremos saber que tipo de columnas tenemos:
df.dtypes

index                    int64
Publishing Year        float64
Book Name               object
Author                  object
language_code           object
Author_Rating           object
Book_average_rating    float64
Book_ratings_count       int64
genre                   object
gross sales            float64
publisher revenue      float64
sale price             float64
sales rank               int64
Publisher               object
units sold               int64
dtype: object

In [191]:
#La columna Publishing Year (a√±o de publicacion) tiene tipo de dato float64 es decir decimal y deberia ser int64 osea entero (los a√±os siempre son numeros enteros)
#Con el metodo .astype() cambiamos el tipo de dato y con el metodo .fillna() logramos que no nos afecte
#los registros que tienen NA
df['Publishing Year'] = df['Publishing Year'].fillna(0).astype('int64')
#Checamos de nuevo nuestros tipos de datos para confirmar que si cambio el tipo de dato de la columna 'Publishing Year'
print(df.dtypes)

index                    int64
Publishing Year          int64
Book Name               object
Author                  object
language_code           object
Author_Rating           object
Book_average_rating    float64
Book_ratings_count       int64
genre                   object
gross sales            float64
publisher revenue      float64
sale price             float64
sales rank               int64
Publisher               object
units sold               int64
dtype: object

In [192]:
#Checamos de nuevo los primeros 5 registros de nuestra base de datos
df.head()
#Ahora si la columna de 'Publishing Year' tiene un tipo de dato adecuado

,index,Publishing Year,Book Name,Author,language_code,Author_Rating,Book_average_rating,Book_ratings_count,genre,gross sales,publisher revenue,sale price,sales rank,Publisher,units sold
0,0,1975,Beowulf,"Unknown, Seamus Heaney",en-US,Novice,3.42,155903,genre fiction,34160.0,20496.0,4.88,1,HarperCollins Publishers,7000
1,1,1987,Batman: Year One,"Frank Miller, David Mazzucchelli, Richmond Lew...",eng,Intermediate,4.23,145267,genre fiction,12437.5,7462.5,1.99,2,HarperCollins Publishers,6250
2,2,2015,Go Set a Watchman,Harper Lee,eng,Novice,3.31,138669,genre fiction,47795.0,28677.0,8.69,3,"Amazon Digital Services, Inc.",5500
3,3,2008,When You Are Engulfed in Flames,David Sedaris,en-US,Intermediate,4.04,150898,fiction,41250.0,24750.0,7.50,3,Hachette Book Group,5500
4,4,2011,Daughter of Smoke & Bone,Laini Taylor,eng,Intermediate,4.04,198283,genre fiction,37952.5,22771.5,7.99,4,Penguin Group (USA) LLC,4750

**Breve explicacion de lo que contiene cada columna:**

Publishing Year: A√±o en que fue publicado el libro

Book name: El titulo del libro

Author: El nombre del autor

Lenguage_code: El idioma en que esta escrito el libro

Author_Rating: Calificacion del autor por sus obras anteriores

Book_average_rating: El promedio de rating calificado por los lectores

Book_ratings_count: El numero de ratings que los lectores dieron al libro

genre: El genero o categoria del libro

gross sales: El total de ganancias de ventas de cada libro

publisher revenue: Los ingresos obtenidos por los editores por la venta de cada libro

sale price: El precio en que se vende cada libro

sales rank: Valor numerico que indica la clasificacion de un libro en funcion de su rendimiento en ventas dentro de su propia categoria

Publisher: Editorial

units sold: Numero total de copias vendidas

Criterios que tomaremos en cuenta para la limpieza de nuestros datos:

In [193]:
#Datos faltantes
#Verificar valores nulos en todas las columnas:
print(df.isnull().sum())
#El resultado nos arroja que la columna 'Book Name' tiene 23 registros nulos y la columna language_code tiene 53

index                   0
Publishing Year         0
Book Name              23
Author                  0
language_code          53
Author_Rating           0
Book_average_rating     0
Book_ratings_count      0
genre                   0
gross sales             0
publisher revenue       0
sale price              0
sales rank              0
Publisher               0
units sold              0
dtype: int64

In [194]:
#Usaremos el metodo .info() para tener mas informacion sobre nuestra base de datos
df.info()
#Vemos que nuestra base de datos tiene 1070 filas y 15 columnas, por lo que valdria la pena eliminar los
#registros nulos, ya que tenemos suficientes datos para seguir trabajando

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1070 entries, 0 to 1069
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   index                1070 non-null   int64
 1   Publishing Year      1070 non-null   int64
 2   Book Name            1047 non-null   object
 3   Author               1070 non-null   object
 4   language_code        1017 non-null   object
 5   Author_Rating        1070 non-null   object
 6   Book_average_rating  1070 non-null   float64
 7   Book_ratings_count   1070 non-null   int64
 8   genre                1070 non-null   object
 9   gross sales          1070 non-null   float64
 10  publisher revenue    1070 non-null   float64
 11  sale price           1070 non-null   float64
 12  sales rank           1070 non-null   int64
 13  Publisher            1070 non-null   object
 14  units sold           1070 non-null   int64
dtypes: float64(4), int64(5), object(6)
memory usage: 125.5+ KB

In [195]:
#Eliminando registros nulos
df.dropna(inplace=True)
#Verificamos de nuevo registros nulos
print(df.isnull().sum())
#Los resultados son favorables, cada vez tenemos una base de datos mas limpia

index                  0
Publishing Year        0
Book Name              0
Author                 0
language_code          0
Author_Rating          0
Book_average_rating    0
Book_ratings_count     0
genre                  0
gross sales            0
publisher revenue      0
sale price             0
sales rank             0
Publisher              0
units sold             0
dtype: int64

In [196]:
#Registros repetidos:
print(df.duplicated().sum())
#El resultado nos indica que no tenemos datos duplicados en nuestra base de datos

0

In [197]:
#Columnas irrelevantes
#Columnas categoricas
columns_to_check_cat = ['Book Name', 'Author', 'language_code', 'Author_Rating', 'genre', 'Publisher ']

In [198]:
#Si alguna columna categorica nos da un valor igual a 1 esta se considera irrelevante, significa que todos los valores
#son iguales
unique_counts = df[columns_to_check_cat].nunique()
print(unique_counts)

Book Name        996
Author           698
language_code      8
Author_Rating      4
genre              4
Publisher          9
dtype: int64

In [199]:
#Otro criterio para eliminar datos irrelevantes es si no nos sirven para contestar nuestras preguntas, por ejemplo la columna
#language_code, todos los libros estan en ingles, no hace la diferencia esa la informacion de esa columna
#Primero exploraremos la columna language_code:
df['language_code'].value_counts()
#Podemos observar que 4 de los diferentes lenguages son el mismo solo que con error tipografico
#y los otros 4 que en total representan 9 filas son insignificantes para nuestras base de datos, por lo tanto esta columna no nos sirve realmente
#para las consultas que queremos hacer

language_code
eng      725
en-US    228
en-GB     29
en-CA      7
fre        4
spa        2
ara        2
nl         1
Name: count, dtype: int64

In [200]:
#Segundo, explorando la columna Author_Rating:
df['Author_Rating'].value_counts()
#A pesar de que son pocas categorias, si nos podrian servir para nuestras consultas y ademas ninguna se repite

Author_Rating
Intermediate    589
Excellent       333
Famous           47
Novice           29
Name: count, dtype: int64

In [201]:
#Tercero, explorando la columna genre:
df['genre'].value_counts()
#De los 4 diferentes generos que nos arroja, dos significan los mismo, en este caso vamos a unificar esos dos generos para tener solo 3 en total
#No eliminaremos esta columna por que creo que podemos necesitar estos datos

genre
genre fiction    772
nonfiction       156
fiction           55
children          15
Name: count, dtype: int64

In [202]:
#Primero hacemos un diccionario con los diferentes subniveles de genero y con el nombre final que queremos que tenga:
unificando_genero = {
    'genre fiction': 'fiction', 'fiction': 'fiction', 'nonfiction': 'no fiction', 'children': 'children'
}

#Codigo para remplazar nombres (aqui usamos el diccionario que hicimos para que reemplace los registros mal nombrados):
#Usamos en metodo de pandas .raplace(dicccionario)
df['genre'] = df['genre'].replace(unificando_genero)
print("DataFrame after replacement:")
df.head()

DataFrame after replacement:

,index,Publishing Year,Book Name,Author,language_code,Author_Rating,Book_average_rating,Book_ratings_count,genre,gross sales,publisher revenue,sale price,sales rank,Publisher,units sold
0,0,1975,Beowulf,"Unknown, Seamus Heaney",en-US,Novice,3.42,155903,fiction,34160.0,20496.0,4.88,1,HarperCollins Publishers,7000
1,1,1987,Batman: Year One,"Frank Miller, David Mazzucchelli, Richmond Lew...",eng,Intermediate,4.23,145267,fiction,12437.5,7462.5,1.99,2,HarperCollins Publishers,6250
2,2,2015,Go Set a Watchman,Harper Lee,eng,Novice,3.31,138669,fiction,47795.0,28677.0,8.69,3,"Amazon Digital Services, Inc.",5500
3,3,2008,When You Are Engulfed in Flames,David Sedaris,en-US,Intermediate,4.04,150898,fiction,41250.0,24750.0,7.50,3,Hachette Book Group,5500
4,4,2011,Daughter of Smoke & Bone,Laini Taylor,eng,Intermediate,4.04,198283,fiction,37952.5,22771.5,7.99,4,Penguin Group (USA) LLC,4750

In [203]:
#Eliminando columnas irrelevantes: language_code
#Usaremos el metodo de pandas .drop()
df = df.drop('language_code', axis=1)
df.head()

,index,Publishing Year,Book Name,Author,Author_Rating,Book_average_rating,Book_ratings_count,genre,gross sales,publisher revenue,sale price,sales rank,Publisher,units sold
0,0,1975,Beowulf,"Unknown, Seamus Heaney",Novice,3.42,155903,fiction,34160.0,20496.0,4.88,1,HarperCollins Publishers,7000
1,1,1987,Batman: Year One,"Frank Miller, David Mazzucchelli, Richmond Lew...",Intermediate,4.23,145267,fiction,12437.5,7462.5,1.99,2,HarperCollins Publishers,6250
2,2,2015,Go Set a Watchman,Harper Lee,Novice,3.31,138669,fiction,47795.0,28677.0,8.69,3,"Amazon Digital Services, Inc.",5500
3,3,2008,When You Are Engulfed in Flames,David Sedaris,Intermediate,4.04,150898,fiction,41250.0,24750.0,7.50,3,Hachette Book Group,5500
4,4,2011,Daughter of Smoke & Bone,Laini Taylor,Intermediate,4.04,198283,fiction,37952.5,22771.5,7.99,4,Penguin Group (USA) LLC,4750

In [204]:
#Nos hemos dado cuenta que la columna publisher nos da error, y tiene datos irrelevantes asi que la vamos a eliminar, pero primero la examinaremos
#df['Publisher'].value_counts() no podemos verla, nos marca error
#df = df.drop('Publisher', axis=1)
#df.head()
#La columna Publisher esta maldita...
df['Publisher '].value_counts()
#Ya encontramos el error, en el nombre tiene un espacio al final que obvio no escribiamos cuando usabamos el nombre de la columna

Publisher
Amazon Digital Services,  Inc.          566
Random House LLC                        111
Penguin Group (USA) LLC                  97
HarperCollins Publishers                 65
Hachette Book Group                      56
Simon and Schuster Digital Sales Inc     55
Macmillan                                40
HarperCollins Publishing                  4
HarperCollins Christian Publishing        4
Name: count, dtype: int64

In [205]:
#Cambiando el nombre de la columna Publisher para corregir el espacio en blanco:
#Usamos el metodo .rename()
df.rename(columns={'Publisher ': 'Editorial'}, inplace=True)
df.head()

,index,Publishing Year,Book Name,Author,Author_Rating,Book_average_rating,Book_ratings_count,genre,gross sales,publisher revenue,sale price,sales rank,Editorial,units sold
0,0,1975,Beowulf,"Unknown, Seamus Heaney",Novice,3.42,155903,fiction,34160.0,20496.0,4.88,1,HarperCollins Publishers,7000
1,1,1987,Batman: Year One,"Frank Miller, David Mazzucchelli, Richmond Lew...",Intermediate,4.23,145267,fiction,12437.5,7462.5,1.99,2,HarperCollins Publishers,6250
2,2,2015,Go Set a Watchman,Harper Lee,Novice,3.31,138669,fiction,47795.0,28677.0,8.69,3,"Amazon Digital Services, Inc.",5500
3,3,2008,When You Are Engulfed in Flames,David Sedaris,Intermediate,4.04,150898,fiction,41250.0,24750.0,7.50,3,Hachette Book Group,5500
4,4,2011,Daughter of Smoke & Bone,Laini Taylor,Intermediate,4.04,198283,fiction,37952.5,22771.5,7.99,4,Penguin Group (USA) LLC,4750

In [206]:
#Unificaremos algunos nombres repetidos de editoriales:
unificando_editorial = {
    'Random House LLC': 'Penguin Random House', 'Penguin Group (USA) LLC': 'Penguin Random House', 'Amazon Digital Services,  Inc.': 'Amazon KDP', 'Simon and Schuster Digital Sales Inc': 'Simon and Schuter',
    'HarperCollins Christian Publishing ': 'HarperCollins Publishing'
}

#Usamos en metodo de pandas .raplace(dicccionario)
df['Editorial'] = df['Editorial'].replace(unificando_editorial)
print("DataFrame after replacement:")
df.head()

DataFrame after replacement:

,index,Publishing Year,Book Name,Author,Author_Rating,Book_average_rating,Book_ratings_count,genre,gross sales,publisher revenue,sale price,sales rank,Editorial,units sold
0,0,1975,Beowulf,"Unknown, Seamus Heaney",Novice,3.42,155903,fiction,34160.0,20496.0,4.88,1,HarperCollins Publishers,7000
1,1,1987,Batman: Year One,"Frank Miller, David Mazzucchelli, Richmond Lew...",Intermediate,4.23,145267,fiction,12437.5,7462.5,1.99,2,HarperCollins Publishers,6250
2,2,2015,Go Set a Watchman,Harper Lee,Novice,3.31,138669,fiction,47795.0,28677.0,8.69,3,Amazon KDP,5500
3,3,2008,When You Are Engulfed in Flames,David Sedaris,Intermediate,4.04,150898,fiction,41250.0,24750.0,7.50,3,Hachette Book Group,5500
4,4,2011,Daughter of Smoke & Bone,Laini Taylor,Intermediate,4.04,198283,fiction,37952.5,22771.5,7.99,4,Penguin Random House,4750

In [207]:
#Haremos un analisis mas profundo de las columnas categoricas:
df = df.sort_values (
    by = 'Book Name'
)
print(df)
#Vemos que hay celdas con simbolos raros

     index  Publishing Year  \
456    456             2011
315    315             1950
489    489             2004
761    761             2005
156    156             2005
..     ...              ...
551    551             2013
568    568             -300
821    821             2007
362    362             2002
652    652             2010

                                             Book Name  \
456                                   A Monster Calls
315                                 Animal Farm & 1984
489                             The Tale of Despereaux
761               'Salem's Lot The Illustrated Edition
156                                               1776
..                                                 ...
551  √®‚Ä∞¬≤√•¬Ω¬©√£‚Äö‚Äô√¶≈í¬Å√£¬Å≈∏√£¬Å¬™√£¬Å‚Äû√•¬§≈°√•¬¥≈Ω√£¬Å¬§√£¬Å¬è√£‚Äö‚Äπ√£¬Å¬®√£‚Ç¨¬Å√•¬Ω¬º√£...
568                         √©¬Å‚Äú√•¬æ¬∑√ß¬∂‚Äú [d√É¬†o d√É¬© j√Ñ¬´ng]
821                       √©¬ª‚Äô√•≈∏¬∑√§¬∫‚Äπ I [Kuroshitsuji I]
362                               √©‚Äπ¬º√£¬Å¬Æ√©≈í¬¨√©‚Ä°‚Äò√®¬°‚Äú√•¬∏¬´ 1
652                                  √©‚Ç¨¬≤√¶‚Äô∆í√£¬Å¬Æ√•¬∑¬®√§¬∫¬∫ 1

                                                Author Author_Rating  \
456                Patrick Ness, Jim Kay, Siobhan Dowd     Excellent
315                George Orwell, Christopher Hitchens     Excellent
489                Kate DiCamillo, Timothy Basil Ering  Intermediate
761                    Stephen King, Jerry N. Uelsmann     Excellent
156                                   David McCullough  Intermediate
..                                                 ...           ...
551                    Haruki Murakami, Philip Gabriel  Intermediate
568  Lao Tzu, Gia-Fu Feng, Jane English, Chungliang...     Excellent
821                           Yana Toboso, Tomo Kimura     Excellent
362                     Hiromu Arakawa, Akira Watanabe        Famous
652                      Hajime Isayama, Sheldon Drzka        Famous

     Book_average_rating  Book_ratings_count       genre  gross sales  \
456                 4.36              104579     fiction      1842.45
315                 4.26              116197     fiction       267.30
489                 4.00              113066     fiction      1153.35
761                 4.25               72797     fiction       770.24
156                 4.06              130293     fiction      7814.40
..                   ...                 ...         ...          ...
551                 3.82               67873     fiction       594.51
568                 4.31               39863     fiction       665.55
821                 4.37               74378  no fiction      1366.86
362                 4.49               93990     fiction       226.71
652                 4.42               82565     fiction       118.80

     publisher revenue  sale price  sales rank             Editorial  \
456           1105.470       10.65         505  Penguin Random House
315              0.000        0.99         338            Amazon KDP
489            692.010        6.99         541  Penguin Random House
761            462.144        6.64         879   Hachette Book Group
156           4688.640       11.84         168  Penguin Random House
..                 ...         ...         ...                   ...
551              0.000        3.99         616            Amazon KDP
568            399.330        4.59         632  Penguin Random House
821            820.116       11.99         960  Penguin Random House
362              0.000        0.99         391            Amazon KDP
652             71.280        0.99         748            Amazon KDP

     units sold
456        4671
315         270
489        4455
761       30672
156         660
..          ...
551        4023
568        3915
821        2889
362        6183
652       42552

[998 rows x 14 columns]

In [210]:
#Queremos eliminar las filas de los nombres raros
df.drop([551, 568, 821, 362, 652], axis=0, inplace=False)
#se supone que aqui elimine las filas con estos indices, luego aparecen mas nombres raros con otros incides, procedemos a eliminarlos ...

,index,Publishing Year,Book Name,Author,Author_Rating,Book_average_rating,Book_ratings_count,genre,gross sales,publisher revenue,sale price,sales rank,Editorial,units sold
456,456,2011,A Monster Calls,"Patrick Ness, Jim Kay, Siobhan Dowd",Excellent,4.36,104579,fiction,1842.45,1105.470,10.65,505,Penguin Random House,4671
315,315,1950,Animal Farm & 1984,"George Orwell, Christopher Hitchens",Excellent,4.26,116197,fiction,267.30,0.000,0.99,338,Amazon KDP,270
489,489,2004,The Tale of Despereaux,"Kate DiCamillo, Timothy Basil Ering",Intermediate,4.00,113066,fiction,1153.35,692.010,6.99,541,Penguin Random House,4455
761,761,2005,'Salem's Lot The Illustrated Edition,"Stephen King, Jerry N. Uelsmann",Excellent,4.25,72797,fiction,770.24,462.144,6.64,879,Hachette Book Group,30672
156,156,2005,1776,David McCullough,Intermediate,4.06,130293,fiction,7814.40,4688.640,11.84,168,Penguin Random House,660
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
739,739,1999,√£‚Äö¬π√£∆í‚Äî√£∆í¬º√£∆íÀÜ√£∆í‚Äπ√£‚Äö¬Ø√£¬Å¬Æ√¶¬Å‚Äπ√§¬∫¬∫ [Sup√Ö¬´toniku no Ko...,"Haruki Murakami, Philip Gabriel",Intermediate,3.82,62229,fiction,1084.59,650.754,9.27,846,Penguin Random House,32616
674,674,1985,√§¬∏‚Äì√ß‚Ä¢≈í√£¬Å¬Æ√ß¬µ‚Äö√£‚Äö≈†√£¬Å¬®√£∆í¬è√£∆í¬º√£∆í‚Ä∞√£∆í≈ì√£‚Äö¬§√£∆í¬´√£∆í‚Ä∞√£∆í¬ª√£∆í¬Ø√£...,"Haruki Murakami, Alfred Birnbaum",Excellent,4.15,63764,fiction,117.81,70.686,0.99,773,Amazon KDP,38016
389,389,2011,√§¬∫¬∫√ß‚Äù≈∏√£¬Å≈í√£¬Å¬®√£¬Å¬ç√£‚Äö¬Å√£¬Å¬è√ß‚Ä∞‚Ä°√£¬Å¬•√£¬Å‚Äò√£¬Å¬Æ√©¬≠‚Äù√¶¬≥‚Ä¢,"Marie Kond√Ö¬ç, Cathy Hirano",Intermediate,3.77,105063,fiction,849.87,509.922,3.99,423,Amazon KDP,5751
279,279,2003,√¶¬°≈ì√®Àú¬≠√©¬´Àú√¶¬†¬°√£∆í‚Ä∫√£‚Äö¬π√£∆íÀÜ√©∆í¬® 1,Bisco Hatori,Excellent,4.36,113881,fiction,666.65,399.990,1.99,299,HarperCollins Publishers,335
969,969,1982,√ß¬æ≈†√£‚Äö‚Äô√£‚Äö¬Å√£¬Å¬ê√£‚Äö‚Äπ√•‚Ä†‚Äô√©‚Ñ¢¬∫ [Hitsujiwomegurub√Ö¬çken],"Haruki Murakami, Alfred Birnbaum",Intermediate,3.94,55262,no fiction,960.29,576.174,8.81,1147,Simon and Schuter,4240

In [211]:
#Eliminando las otras filas con nombres raros
df.drop([739, 674, 389, 279,969], axis=0, inplace=False)
#y aparecen los anteriores ... quiero morir

,index,Publishing Year,Book Name,Author,Author_Rating,Book_average_rating,Book_ratings_count,genre,gross sales,publisher revenue,sale price,sales rank,Editorial,units sold
456,456,2011,A Monster Calls,"Patrick Ness, Jim Kay, Siobhan Dowd",Excellent,4.36,104579,fiction,1842.45,1105.470,10.65,505,Penguin Random House,4671
315,315,1950,Animal Farm & 1984,"George Orwell, Christopher Hitchens",Excellent,4.26,116197,fiction,267.30,0.000,0.99,338,Amazon KDP,270
489,489,2004,The Tale of Despereaux,"Kate DiCamillo, Timothy Basil Ering",Intermediate,4.00,113066,fiction,1153.35,692.010,6.99,541,Penguin Random House,4455
761,761,2005,'Salem's Lot The Illustrated Edition,"Stephen King, Jerry N. Uelsmann",Excellent,4.25,72797,fiction,770.24,462.144,6.64,879,Hachette Book Group,30672
156,156,2005,1776,David McCullough,Intermediate,4.06,130293,fiction,7814.40,4688.640,11.84,168,Penguin Random House,660
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
551,551,2013,√®‚Ä∞¬≤√•¬Ω¬©√£‚Äö‚Äô√¶≈í¬Å√£¬Å≈∏√£¬Å¬™√£¬Å‚Äû√•¬§≈°√•¬¥≈Ω√£¬Å¬§√£¬Å¬è√£‚Äö‚Äπ√£¬Å¬®√£‚Ç¨¬Å√•¬Ω¬º√£...,"Haruki Murakami, Philip Gabriel",Intermediate,3.82,67873,fiction,594.51,0.000,3.99,616,Amazon KDP,4023
568,568,-300,√©¬Å‚Äú√•¬æ¬∑√ß¬∂‚Äú [d√É¬†o d√É¬© j√Ñ¬´ng],"Lao Tzu, Gia-Fu Feng, Jane English, Chungliang...",Excellent,4.31,39863,fiction,665.55,399.330,4.59,632,Penguin Random House,3915
821,821,2007,√©¬ª‚Äô√•≈∏¬∑√§¬∫‚Äπ I [Kuroshitsuji I],"Yana Toboso, Tomo Kimura",Excellent,4.37,74378,no fiction,1366.86,820.116,11.99,960,Penguin Random House,2889
362,362,2002,√©‚Äπ¬º√£¬Å¬Æ√©≈í¬¨√©‚Ä°‚Äò√®¬°‚Äú√•¬∏¬´ 1,"Hiromu Arakawa, Akira Watanabe",Famous,4.49,93990,fiction,226.71,0.000,0.99,391,Amazon KDP,6183
652,652,2010,√©‚Ç¨¬≤√¶‚Äô∆í√£¬Å¬Æ√•¬∑¬®√§¬∫¬∫ 1,"Hajime Isayama, Sheldon Drzka",Famous,4.42,82565,fiction,118.80,71.280,0.99,748,Amazon KDP,42552

In [ ]:
#Columnas numericas
#Para saber si una columna numerica es irrelevante checamos su desviacion estandar, si esta es igual a cero
#quiere decir que los valores en esa columna son iguales, no hay variacion de numeros, osea es irrelevante
df.describe()
#El metodo .describe() por default toma solo las columnas de valor numerico
#No hay columnas numericas con desviacion estandar igual a cero
#Los valores repetidos en las columnas numericas si pueden ser
#Nos damos cuenta que la columna Publishing Year tiene numeros negativos y esos datos no los tomaremos en cuenta para responder nuestras preguntas

,index,Publishing Year,Book_average_rating,Book_ratings_count,gross sales,publisher revenue,sale price,sales rank,units sold
count,1070.000000,1069.000000,1070.000000,1070.000000,1070.000000,1070.000000,1070.000000,1070.000000,1070.000000
mean,534.500000,1971.377923,4.007000,94909.913084,1856.622944,843.281030,4.869561,611.652336,9676.980374
std,309.026698,185.080257,0.247244,31513.242518,3936.924240,2257.596743,3.559919,369.849830,15370.571306
min,0.000000,-560.000000,2.970000,27308.000000,104.940000,0.000000,0.990000,1.000000,106.000000
25%,267.250000,1985.000000,3.850000,70398.000000,372.465000,0.000000,1.990000,287.500000,551.250000
50%,534.500000,2003.000000,4.015000,89309.000000,809.745000,273.078000,3.990000,595.500000,3924.000000
75%,801.750000,2010.000000,4.170000,113906.500000,1487.957500,721.180500,6.990000,932.500000,5312.250000
max,1069.000000,2016.000000,4.770000,206792.000000,47795.000000,28677.000000,33.860000,1273.000000,61560.000000

In [ ]:
#Limpieza de datos negativos
df = df[(df['Publishing Year'] >= 0)]
df.describe()

,index,Publishing Year,Book_average_rating,Book_ratings_count,gross sales,publisher revenue,sale price,sales rank,units sold
count,992.000000,992.000000,992.000000,992.000000,992.000000,992.000000,992.000000,992.000000,992.000000
mean,529.364919,1985.137097,4.003740,95573.408266,1892.022228,851.842609,4.848216,605.477823,9770.614919
std,308.889816,56.607571,0.247256,31664.722436,4033.950983,2309.802428,3.588222,369.491465,15461.295069
min,0.000000,1308.000000,2.970000,27308.000000,104.940000,0.000000,0.990000,1.000000,106.000000
25%,262.750000,1985.000000,3.850000,70997.500000,371.127500,0.000000,1.990000,282.750000,566.250000
50%,529.500000,2003.000000,4.010000,90051.500000,812.105000,261.813000,3.990000,590.000000,3924.000000
75%,794.250000,2010.000000,4.170000,115679.500000,1496.342500,722.500500,6.990000,920.250000,5406.750000
max,1069.000000,2016.000000,4.770000,206792.000000,47795.000000,28677.000000,33.860000,1273.000000,61560.000000

In [ ]:
#Una vez teniendo la base de datos limpia, podemos hacer consultas.
# 1.-¬øCual es el libro con mayor calificacion promedio? (Book_average_rating)
book_best_rating = df.loc[df['Book_average_rating'].idxmax(),]
print(f'El libro con mayor calificacion promedio es: {book_best_rating}')

El libro con mayor calificacion promedio es: index                                       331
Publishing Year                            2014
Book Name                     Words of Radiance
Author                        Brandon Sanderson
Author_Rating                            Famous
Book_average_rating                        4.77
Book_ratings_count                        73572
genre                                   fiction
gross sales                              741.52
publisher revenue                       444.912
sale price                                 2.99
sales rank                                  354
Editorial              HarperCollins Publishers
units sold                                  248
Name: 331, dtype: object

In [ ]:
#2.-Que editorial tiene